version: '3.7'

services:
  nodejs:
    container_name: nodejs
    image: nodejs
    restart: unless-stopped
    build:
      context: ./app
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 5m
      timeout: 5s
      retries: 3
      start_period: 15s

  caddy:
    container_name: caddy2
    restart: unless-stopped
    depends_on:
      - nodejs
    build:
      context: ./caddy
      dockerfile: ./Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/caddy_data:/data
      - ./data/caddy_config:/config
    environment:
      PROXY_BACKEND: nodejs
      PROXY_PORT: 3000
      DOMAIN: ${DOMAIN}

volumes:
  caddy_data:
  caddy_config:
